// Generated by tools/build-module-set.py from tools/module-sets/ansible.posix.json and ansible-doc.
// Edit the spec and regenerate rather than changing this file by hand.
Scransible.registerModuleSet({
  "collection": "ansible.posix",
  "title": "POSIX",
  "version": "2.2.2",
  "modules": [
    {
      "name": "ansible.posix.authorized_key",
      "short": "authorized_key",
      "category": "access",
      "description": "Adds or removes an SSH authorized key",
      "palette": ["user", "key"],
      "args": {
        "key": {"kind": "str", "required": true, "doc": "The SSH public key(s), as a string or (since Ansible 1.9) url (https://github.com/username.keys)"},
        "user": {"kind": "str", "required": true, "doc": "The username on the remote host whose authorized_keys file will be modified"},
        "comment": {"kind": "str", "doc": "Change the comment on the public key"},
        "exclusive": {"kind": "bool", "default": false, "doc": "Whether to remove all other non-specified keys from the authorized_keys file"},
        "follow": {"kind": "bool", "default": false, "doc": "Follow path symlink instead of replacing it"},
        "key_options": {"kind": "str", "doc": "A string of ssh key options to be prepended to the key in the authorized_keys file"},
        "manage_dir": {"kind": "bool", "default": true, "doc": "Whether this module should manage the directory of the authorized key file"},
        "path": {"kind": "str", "doc": "Alternative path to the authorized_keys file"},
        "state": {"kind": "choice", "choices": ["absent", "present"], "default": "present", "doc": "Whether the given key (with the given key_options) should or should not be in the file"},
        "validate_certs": {"kind": "bool", "default": true, "doc": "This only applies if using a https url as the source of the keys"}
      }
    },
    {
      "name": "ansible.posix.firewalld",
      "short": "firewalld",
      "category": "access",
      "description": "Manage arbitrary ports/services with firewalld",
      "palette": ["service", "state", "permanent"],
      "defaults": {"state": "enabled"},
      "args": {
        "state": {"kind": "choice", "required": true, "choices": ["absent", "disabled", "enabled", "present"], "doc": "Enable or disable a setting"},
        "forward": {"kind": "bool", "doc": "The forward setting you would like to enable/disable to/from zones within firewalld"},
        "icmp_block": {"kind": "str", "doc": "The ICMP block you would like to add/remove to/from a zone in firewalld"},
        "icmp_block_inversion": {"kind": "bool", "doc": "Enable/Disable inversion of ICMP blocks for a zone in firewalld"},
        "immediate": {"kind": "bool", "default": false, "doc": "Whether to apply this change to the runtime firewalld configuration"},
        "interface": {"kind": "str", "doc": "The interface you would like to add/remove to/from a zone in firewalld"},
        "masquerade": {"kind": "bool", "doc": "The masquerade setting you would like to enable/disable to/from zones within firewalld"},
        "offline": {"kind": "bool", "default": false, "doc": "Ignores O(immediate) if O(permanent=true) and firewalld is not running"},
        "permanent": {"kind": "bool", "default": false, "doc": "Whether to apply this change to the permanent firewalld configuration"},
        "port": {"kind": "str", "doc": "Name of a port or port range to add/remove to/from firewalld"},
        "port_forward": {"kind": "yaml", "empty": [], "doc": "Port and protocol to forward using firewalld"},
        "protocol": {"kind": "str", "doc": "Name of a protocol to add/remove to/from firewalld"},
        "rich_rule": {"kind": "str", "doc": "Rich rule to add/remove to/from firewalld"},
        "service": {"kind": "str", "doc": "Name of a service to add/remove to/from firewalld"},
        "source": {"kind": "str", "doc": "The source/network you would like to add/remove to/from firewalld"},
        "target": {"kind": "choice", "choices": ["default", "ACCEPT", "DROP", "%%REJECT%%"], "doc": "firewalld Zone target"},
        "timeout": {"kind": "int", "doc": "The amount of time in seconds the rule should be in effect for when non-permanent"},
        "zone": {"kind": "str", "doc": "The firewalld zone to add/remove to/from"}
      }
    },
    {
      "name": "ansible.posix.sysctl",
      "short": "sysctl",
      "category": "utilities",
      "description": "Manage entries in sysctl.conf",
      "palette": ["name", "value"],
      "args": {
        "name": {"kind": "str", "required": true, "aliases": ["key"], "doc": "The dot-separated path (also known as O(key)) specifying the sysctl variable"},
        "ignoreerrors": {"kind": "bool", "default": false, "doc": "Use this option to ignore errors about unknown keys"},
        "reload": {"kind": "bool", "default": true, "doc": "If V(true), performs a C(/sbin/sysctl -p) if the O(sysctl_file) is updated"},
        "state": {"kind": "choice", "choices": ["present", "absent"], "default": "present", "doc": "Whether the entry should be present or absent in the sysctl file"},
        "sysctl_file": {"kind": "str", "doc": "Specifies the absolute path to C(sysctl.conf), if not C(/etc/sysctl.conf)"},
        "sysctl_set": {"kind": "bool", "default": false, "doc": "Verify token value with the sysctl command and set with C(-w) if necessary"},
        "value": {"kind": "str", "aliases": ["val"], "doc": "Desired value of the sysctl key"}
      }
    }
  ]
});
