// Generated by tools/build-module-set.py from tools/module-sets/cisco.nxos.json and ansible-doc.
// Edit the spec and regenerate rather than changing this file by hand.
Scransible.registerModuleSet({
  "collection": "cisco.nxos",
  "title": "Cisco NX-OS",
  "version": "13.0.0",
  "categories": [{"id": "network", "name": "Network", "color": "#4CC3E6"}],
  "modules": [
    {
      "name": "cisco.nxos.nxos_config",
      "short": "nxos_config",
      "category": "network",
      "description": "Manage Cisco NXOS configuration sections",
      "palette": ["parents", "lines"],
      "label": "NXOS Config",
      "args": {
        "after": {"kind": "list", "doc": "The ordered set of commands to append to the end of the command stack if a change needs to be made"},
        "backup": {"kind": "bool", "default": false, "doc": "This argument will cause the module to create a full backup of the current C(running-config) from the remote device before any changes are made"},
        "backup_options": {"kind": "yaml", "empty": {}, "doc": "This is a dict object containing configurable options related to backup file path"},
        "before": {"kind": "list", "doc": "The ordered set of commands to push on to the command stack if a change needs to be made"},
        "content": {"kind": "str", "doc": "Configuration content to apply to the device"},
        "defaults": {"kind": "bool", "default": false, "doc": "The I(defaults) argument will influence how the running-config is collected from the device"},
        "diff_against": {"kind": "choice", "choices": ["startup", "intended", "running"], "doc": "When using the C(ansible-playbook --diff) command line argument the module can generate diffs against different sources"},
        "diff_ignore_lines": {"kind": "list", "doc": "Use this argument to specify one or more lines that should be ignored during the diff"},
        "intended_config": {"kind": "str", "doc": "The C(intended_config) provides the master configuration that the node should conform to and is used to check the final running-config against"},
        "lines": {"kind": "list", "aliases": ["commands"], "doc": "The ordered set of commands that should be configured in the section"},
        "match": {"kind": "choice", "choices": ["line", "strict", "exact", "none"], "default": "line", "doc": "Instructs the module on the way to perform the matching of the set of commands against the current device config"},
        "parents": {"kind": "list", "doc": "The ordered set of parents that uniquely identify the section or hierarchy the commands should be checked against"},
        "replace": {"kind": "choice", "choices": ["line", "block", "config"], "default": "line", "doc": "Instructs the module on the way to perform the configuration on the device"},
        "replace_src": {"kind": "str", "doc": "The I(replace_src) argument provides path to the configuration file to load into the remote system"},
        "running_config": {"kind": "str", "aliases": ["config"], "doc": "The module, by default, will connect to the remote device and retrieve the current running-config to use as a base for comparing against the contents of source"},
        "save_when": {"kind": "choice", "choices": ["always", "never", "modified", "changed"], "default": "never", "doc": "When changes are made to the device running-configuration, the changes are not copied to non-volatile storage by default"},
        "src": {"kind": "str", "doc": "Specifies the source path to the file that contains the configuration or configuration template to load"}
      }
    },
    {
      "name": "cisco.nxos.nxos_command",
      "short": "nxos_command",
      "category": "network",
      "description": "Run arbitrary command on Cisco NXOS devices",
      "palette": ["commands"],
      "label": "NXOS Command",
      "args": {
        "commands": {"kind": "list", "required": true, "doc": "The commands to send to the remote NXOS device"},
        "interval": {"kind": "int", "doc": "Configures the interval in seconds to wait between retries of the command"},
        "match": {"kind": "choice", "choices": ["any", "all"], "default": "all", "doc": "The I(match) argument is used in conjunction with the I(wait_for) argument to specify the match policy"},
        "retries": {"kind": "int", "doc": "Specifies the number of retries a command should by tried before it is considered failed"},
        "wait_for": {"kind": "list", "aliases": ["waitfor"], "doc": "Specifies what to evaluate from the output of the command and what conditionals to apply"}
      }
    },
    {
      "name": "cisco.nxos.nxos_facts",
      "short": "nxos_facts",
      "category": "network",
      "description": "Gets facts about NX-OS switches",
      "palette": ["gather_subset"],
      "label": "NXOS Facts",
      "args": {
        "available_network_resources": {"kind": "bool", "default": false, "doc": "When set to C(true) a list of network resources for which resource modules are available will be provided"},
        "gather_network_resources": {"kind": "list", "doc": "When supplied, this argument will gather configuration facts only for the given subset"},
        "gather_subset": {"kind": "list", "doc": "When supplied, this argument will gather operational facts only for the given subset"}
      }
    },
    {
      "name": "cisco.nxos.nxos_interfaces",
      "short": "nxos_interfaces",
      "category": "network",
      "description": "Interfaces resource module",
      "palette": ["config", "state"],
      "label": "NXOS Interfaces",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of interface options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "gathered", "rendered", "parsed", "purged"], "default": "merged", "doc": "The state of the configuration after module completion The state I(rendered) considers the system default mode for interfaces to be \"Layer 3\" and the system def"}
      }
    },
    {
      "name": "cisco.nxos.nxos_l3_interfaces",
      "short": "nxos_l3_interfaces",
      "category": "network",
      "description": "L3 interfaces resource module",
      "palette": ["config", "state"],
      "label": "NXOS L3 Interfaces",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of Layer-3 interface options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "rendered", "gathered", "parsed"], "default": "merged", "doc": "The state the configuration should be left in The states I(rendered), I(gathered) and I(parsed) does not perform any change on the device"}
      }
    },
    {
      "name": "cisco.nxos.nxos_vlans",
      "short": "nxos_vlans",
      "category": "network",
      "description": "VLANs resource module",
      "palette": ["config", "state"],
      "label": "NXOS VLANs",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of Vlan options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "gathered", "rendered", "parsed"], "default": "merged", "doc": "The state of the configuration after module completion"}
      }
    }
  ]
});
