// Generated by tools/build-module-set.py from tools/module-sets/cisco.ios.json and ansible-doc.
// Edit the spec and regenerate rather than changing this file by hand.
Scransible.registerModuleSet({
  "collection": "cisco.ios",
  "title": "Cisco IOS",
  "version": "11.6.0",
  "categories": [{"id": "network", "name": "Network", "color": "#4CC3E6"}],
  "modules": [
    {
      "name": "cisco.ios.ios_config",
      "short": "ios_config",
      "category": "network",
      "description": "Module to manage configuration sections",
      "palette": ["parents", "lines"],
      "label": "IOS Config",
      "args": {
        "after": {"kind": "list", "doc": "The ordered set of commands to append to the end of the command stack if a change needs to be made"},
        "backup": {"kind": "bool", "default": false, "doc": "This argument will cause the module to create a full backup of the current C(running-config) from the remote device before any changes are made"},
        "backup_options": {"kind": "yaml", "empty": {}, "doc": "This is a dict object containing configurable options related to backup file path"},
        "before": {"kind": "list", "doc": "The ordered set of commands to push on to the command stack if a change needs to be made"},
        "content": {"kind": "str", "doc": "Configuration content to apply to the device"},
        "defaults": {"kind": "bool", "default": false, "doc": "This argument specifies whether or not to collect all defaults when getting the remote device running config"},
        "diff_against": {"kind": "choice", "choices": ["running", "startup", "intended"], "doc": "When using the C(ansible-playbook --diff) command line argument the module can generate diffs against different sources"},
        "diff_ignore_lines": {"kind": "list", "doc": "Use this argument to specify one or more lines that should be ignored during the diff"},
        "intended_config": {"kind": "str", "doc": "The C(intended_config) provides the master configuration that the node should conform to and is used to check the final running-config against"},
        "lines": {"kind": "list", "aliases": ["commands"], "doc": "The ordered set of commands that should be configured in the section"},
        "match": {"kind": "choice", "choices": ["line", "strict", "exact", "none"], "default": "line", "doc": "Instructs the module on the way to perform the matching of the set of commands against the current device config"},
        "multiline_delimiter": {"kind": "str", "doc": "This argument is used when pushing a multiline configuration element to the IOS device"},
        "parents": {"kind": "list", "doc": "The ordered set of parents that uniquely identify the section or hierarchy the commands should be checked against"},
        "replace": {"kind": "choice", "choices": ["line", "block"], "default": "line", "doc": "Instructs the module on the way to perform the configuration on the device"},
        "running_config": {"kind": "str", "aliases": ["config"], "doc": "The module, by default, will connect to the remote device and retrieve the current running-config to use as a base for comparing against the contents of source"},
        "save_when": {"kind": "choice", "choices": ["always", "never", "modified", "changed"], "default": "never", "doc": "When changes are made to the device running-configuration, the changes are not copied to non-volatile storage by default"},
        "src": {"kind": "str", "doc": "Specifies the source path to the file that contains the configuration or configuration template to load"}
      }
    },
    {
      "name": "cisco.ios.ios_command",
      "short": "ios_command",
      "category": "network",
      "description": "Module to run commands on remote devices",
      "palette": ["commands"],
      "label": "IOS Command",
      "args": {
        "commands": {"kind": "list", "required": true, "doc": "List of commands to send to the remote ios device over the configured provider"},
        "interval": {"kind": "int", "doc": "Configures the interval in seconds to wait between retries of the command"},
        "match": {"kind": "choice", "choices": ["any", "all"], "default": "all", "doc": "The I(match) argument is used in conjunction with the I(wait_for) argument to specify the match policy"},
        "retries": {"kind": "int", "doc": "Specifies the number of retries a command should by tried before it is considered failed"},
        "wait_for": {"kind": "list", "aliases": ["waitfor"], "doc": "List of conditions to evaluate against the output of the command"}
      }
    },
    {
      "name": "cisco.ios.ios_facts",
      "short": "ios_facts",
      "category": "network",
      "description": "Module to collect facts from remote devices",
      "palette": ["gather_subset"],
      "label": "IOS Facts",
      "args": {
        "available_network_resources": {"kind": "bool", "default": false, "doc": "When 'True' a list of network resources for which resource modules are available will be provided"},
        "gather_network_resources": {"kind": "list", "doc": "When supplied, this argument will restrict the facts collected to a given subset"},
        "gather_subset": {"kind": "list", "doc": "When supplied, this argument restricts the facts collected to a given subset"}
      }
    },
    {
      "name": "cisco.ios.ios_interfaces",
      "short": "ios_interfaces",
      "category": "network",
      "description": "Resource module to configure interfaces",
      "palette": ["config", "state"],
      "label": "IOS Interfaces",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of interface options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "rendered", "gathered", "purged", "parsed"], "default": "merged", "doc": "The state the configuration should be left in The states I(rendered), I(gathered) and I(parsed) does not perform any change on the device"}
      }
    },
    {
      "name": "cisco.ios.ios_l3_interfaces",
      "short": "ios_l3_interfaces",
      "category": "network",
      "description": "Resource module to configure L3 interfaces",
      "palette": ["config", "state"],
      "label": "IOS L3 Interfaces",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of Layer-3 interface options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "rendered", "gathered", "parsed"], "default": "merged", "doc": "The state the configuration should be left in The states I(rendered), I(gathered) and I(parsed) does not perform any change on the device"}
      }
    },
    {
      "name": "cisco.ios.ios_vlans",
      "short": "ios_vlans",
      "category": "network",
      "description": "Resource module to configure VLANs",
      "palette": ["config", "state"],
      "label": "IOS VLANs",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of VLANs options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "rendered", "gathered", "purged", "parsed"], "default": "merged", "doc": "The state the configuration should be left in The states I(rendered), I(gathered) and I(parsed) does not perform any change on the device"}
      }
    },
    {
      "name": "cisco.ios.ios_static_routes",
      "short": "ios_static_routes",
      "category": "network",
      "description": "Resource module to configure static routes",
      "palette": ["config", "state"],
      "label": "IOS Static Routes",
      "defaults": {"state": "merged"},
      "args": {
        "config": {"kind": "yaml", "empty": [], "doc": "A dictionary of static route options"},
        "running_config": {"kind": "str", "doc": "This option is used only with state I(parsed)"},
        "state": {"kind": "choice", "choices": ["merged", "replaced", "overridden", "deleted", "gathered", "rendered", "parsed"], "default": "merged", "doc": "The state the configuration should be left in The states I(rendered), I(gathered) and I(parsed) does not perform any change on the device"}
      }
    }
  ]
});
