// Generated by tools/build-module-set.py from tools/module-sets/community.general.json and ansible-doc.
// Edit the spec and regenerate rather than changing this file by hand.
Scransible.registerModuleSet({
  "collection": "community.general",
  "title": "Community general",
  "version": "13.4.0",
  "modules": [
    {
      "name": "community.general.ufw",
      "short": "ufw",
      "category": "access",
      "description": "Manage firewall with UFW",
      "palette": ["rule", "to_port", "proto"],
      "defaults": {"rule": "allow", "proto": "tcp"},
      "args": {
        "comment": {"kind": "str", "doc": "Add a comment to the rule"},
        "default": {"kind": "choice", "aliases": ["policy"], "choices": ["allow", "deny", "reject"], "doc": "Change the default policy for incoming or outgoing traffic"},
        "delete": {"kind": "bool", "default": false, "doc": "Delete rule"},
        "direction": {"kind": "choice", "choices": ["in", "incoming", "out", "outgoing", "routed"], "doc": "Select direction for a rule or default policy command"},
        "from_ip": {"kind": "str", "aliases": ["from", "src"], "doc": "Source IP address"},
        "from_port": {"kind": "str", "doc": "Source port"},
        "insert": {"kind": "int", "doc": "Insert the corresponding rule as rule number NUM"},
        "insert_relative_to": {"kind": "choice", "choices": ["first-ipv4", "first-ipv6", "last-ipv4", "last-ipv6", "zero"], "default": "zero", "doc": "Allows to interpret the index in O(insert) relative to a position"},
        "interface": {"kind": "str", "aliases": ["if"], "doc": "Specify interface for the rule"},
        "interface_in": {"kind": "str", "aliases": ["if_in"], "doc": "Specify input interface for the rule"},
        "interface_out": {"kind": "str", "aliases": ["if_out"], "doc": "Specify output interface for the rule"},
        "log": {"kind": "bool", "default": false, "doc": "Log new connections matched to this rule"},
        "logging": {"kind": "choice", "choices": ["on", "off", "low", "medium", "high", "full"], "doc": "Toggles logging"},
        "name": {"kind": "str", "aliases": ["app"], "doc": "Use profile located in C(/etc/ufw/applications.d)"},
        "proto": {"kind": "choice", "aliases": ["protocol"], "choices": ["any", "tcp", "udp", "ipv6", "esp", "ah", "gre", "igmp", "vrrp"], "doc": "TCP/IP protocol"},
        "route": {"kind": "bool", "default": false, "doc": "Apply the rule to routed/forwarded packets"},
        "rule": {"kind": "choice", "choices": ["allow", "deny", "limit", "reject"], "doc": "Add firewall rule"},
        "state": {"kind": "choice", "choices": ["disabled", "enabled", "reloaded", "reset"], "doc": "V(enabled) reloads firewall and enables firewall on boot"},
        "to_ip": {"kind": "str", "aliases": ["dest", "to"], "doc": "Destination IP address"},
        "to_port": {"kind": "str", "aliases": ["port"], "doc": "Destination port"}
      }
    },
    {
      "name": "community.general.timezone",
      "short": "timezone",
      "category": "utilities",
      "description": "Configure timezone setting",
      "palette": ["name"],
      "args": {
        "hwclock": {"kind": "choice", "aliases": ["rtc"], "choices": ["local", "UTC"], "doc": "Whether the hardware clock is in UTC or in local timezone"},
        "name": {"kind": "str", "doc": "Name of the timezone for the system clock"}
      }
    }
  ]
});
