// Export: choose a format and YAML style, preview every file, run the checks, then
// download plain Ansible (a playbook, a project .zip, or a role .tar.gz).
(function () {
  const SX = window.Scransible;
  const { el, icon, ui, Blocks: B, Ansible: A } = SX;
  const store = SX.store;
  const KIND_COLORS = { playbook: '#F4C542', config: '#C3CCDB', requirements: '#C3CCDB', inventory: '#5FA8FF', vars: '#E2CBA4', role: '#F08BD8', template: '#33CFB0', layout: '#6B7280' };
  const state = { file: null };
  let root;

  const project = () => store.project;
  const settings = () => project().settings;

  function setSetting(key, value) {
    store.commit(p => { p.settings[key] = value; }, { checkpoint: false, source: 'export' });
  }

  function exportRole() {
    return project().roles.find(r => r.name === settings().exportRole) || project().roles[0] || null;
  }

  function scope() {
    const s = settings();
    if (s.format === 'yml') {
      const pb = SX.activePlaybook(project());
      return { kind: 'yml', name: pb.path.split('/').pop(), where: [pb.path], files: [{ path: pb.path, kind: 'playbook', content: A.playbookYaml(pb, s, '# Generated by Scransible\n---\n').text }] };
    }
    if (s.format === 'role') {
      const role = exportRole();
      if (!role) return { kind: 'role', name: 'role.tar.gz', where: [], files: [] };
      return { kind: 'role', name: `${role.name}.tar.gz`, where: [`roles/${role.name}`], files: A.roleFiles(role, s, `${role.name}/`) };
    }
    return { kind: 'zip', name: `${project().name}.zip`, where: null, files: A.projectFiles(project(), s) };
  }

  function issuesFor(sc) {
    const all = SX.Lint.run(project()).issues;
    return sc.where ? all.filter(i => sc.where.includes(i.where)) : all;
  }

  // ---- Left: options ------------------------------------------------------------------------

  function radioCard(value, title, ext, desc) {
    const checked = settings().format === value;
    return el('button', { class: 'radio-card', type: 'button', attrs: { role: 'radio', 'aria-checked': String(checked) }, onclick: () => { state.file = null; setSetting('format', value); } }, [
      el('span', { class: 'dot' }),
      el('span', {}, [el('span', { class: 'rc-title' }, [title, el('span', { class: 'mono', text: ext })]), el('span', { class: 'rc-desc', style: 'display: block', text: desc })])
    ]);
  }

  function optionsPanel() {
    const s = settings();
    const switchRow = (key, label, hint, sub) => {
      const id = ui.fieldId();
      return el('div', { style: 'display: flex; flex-direction: column; gap: 4px' }, [
        el('div', { class: 'inline-field' }, [el('span', { id, style: 'font: 600 13px/1.2 var(--font-ui)', text: label }), ui.switchEl(!!s[key], v => setSetting(key, v), id)]),
        sub ? el('span', { class: 'mono faint', style: 'font-size: 12px', text: sub }) : null,
        hint ? el('span', { class: 'field-hint', text: hint }) : null
      ]);
    };
    const roles = project().roles;
    const builtin = SX.moduleSets.find(m => m.collection === 'ansible.builtin');
    return el('section', { class: 'side', attrs: { 'aria-label': 'Export options' } }, el('div', { class: 'side-pad' }, [
      el('h2', { class: 'panel-title', text: 'Export as' }),
      el('div', { style: 'display: flex; flex-direction: column; gap: 10px', attrs: { role: 'radiogroup', 'aria-label': 'Export as' } }, [
        radioCard('yml', 'Playbook file', '.yml', `Just ${SX.activePlaybook(project()).path} — drop it into an existing Ansible repo.`),
        radioCard('zip', 'Project archive', '.zip', 'Playbooks, roles, inventory, group_vars, ansible.cfg and requirements.yml — ready to run.'),
        radioCard('role', 'Single role', '.tar.gz', roles.length ? 'Package one role in Galaxy layout to share or publish.' : 'This project has no roles yet.')
      ]),
      s.format === 'role' && roles.length ? ui.field('Role', ui.select(roles.map(r => [r.name, r.name]), exportRole()?.name, v => { state.file = null; setSetting('exportRole', v); }, { cls: 'select tall mono' })) : null,
      el('h2', { class: 'panel-title', style: 'margin-top: 8px', text: 'YAML style' }),
      switchRow('fqcn', 'Fully-qualified module names', null, s.fqcn ? 'ansible.builtin.apt' : 'apt'),
      s.format === 'zip' ? switchRow('keepLayout', 'Keep block layout', 'Adds .scransible/layout.json so a re-import puts every block back where you left it. Ansible ignores it.') : null,
      el('div', { style: 'display: grid; grid-template-columns: 1fr 1fr; gap: 10px' }, [
        ui.field('Quote strings', ui.select([['needed', 'When needed'], ['always', 'Always']], s.quote, v => setSetting('quote', v), { cls: 'select tall' })),
        ui.field('Indent', ui.select([['2', '2 spaces'], ['4', '4 spaces']], String(s.indent), v => setSetting('indent', Number(v)), { cls: 'select tall' }))
      ]),
      el('p', { class: 'field-hint', text: `Checks use the module docs from ansible-core ${builtin?.version || ''} and the installed module sets.` })
    ]));
  }

  // ---- Middle: files --------------------------------------------------------------------------

  function decorations(file) {
    if (file.kind !== 'playbook' && !/tasks\/main\.yml$|handlers\/main\.yml$/.test(file.path)) return null;
    let parsed;
    try {
      parsed = file.kind === 'playbook' ? A.parsePlaybook(file.content) : A.parseTasksText(file.content);
    } catch (error) {
      return null;
    }
    const colors = new Map();
    SX.walk(parsed.items, node => {
      const r = parsed.ranges.get(node.id);
      if (!r) return;
      const color = B.colorOf(node) || '#C3CCDB';
      for (let n = r.start; n <= r.end; n++) {
        const current = colors.get(n);
        if (!current || current.size >= r.end - r.start) colors.set(n, { color, size: r.end - r.start });
      }
    });
    return n => ({ gut: colors.get(n)?.color });
  }

  function filesPane(sc) {
    const file = sc.files.find(f => f.path === state.file) || sc.files[0];
    if (!file) return el('section', { style: 'display: flex; align-items: center; justify-content: center' }, el('p', { class: 'empty-note', text: 'Nothing to export yet.' }));
    state.file = file.path;
    const viewer = ui.codeView(file.content, { decorate: decorations(file) });
    viewer.style.flex = '1';
    return el('section', { style: 'background: var(--bg); display: flex; flex-direction: column; min-height: 0; min-width: 0; border-right: 1px solid var(--border)', attrs: { 'aria-label': 'Files' } }, [
      el('div', { class: 'file-tabs', attrs: { role: 'tablist' } }, sc.files.map(f => el('button', {
        type: 'button', text: f.path, attrs: { role: 'tab', 'aria-selected': String(f.path === file.path) }, onclick: () => { state.file = f.path; render(); }
      }))),
      viewer
    ]);
  }

  // ---- Right: checks and contents ------------------------------------------------------------

  function lineOf(sc, issue) {
    const node = issue.nodeId && SX.findNode(project(), issue.nodeId);
    const file = sc.files.find(f => f.kind === 'playbook' || f.kind === 'role');
    if (!node?.name) return issue.where;
    for (const f of sc.files) {
      const index = f.content.split('\n').findIndex(line => line.trim() === `- name: ${node.name}` || line.trim() === `- name: "${node.name}"`);
      if (index >= 0) return `${f.path}:${index + 1}`;
    }
    return file ? file.path : issue.where;
  }

  function showBlock(issue) {
    const located = SX.locate(project(), issue.nodeId);
    store.commit(p => {
      const pb = p.playbooks.find(x => SX.locate({ playbooks: [x], roles: [] }, issue.nodeId));
      if (pb) SX.openPlaybook(p, pb.id);
      else {
        const role = p.roles.find(r => SX.locate({ playbooks: [], roles: [r] }, issue.nodeId));
        if (role) SX.openRole(p, role.id);
      }
    }, { checkpoint: false });
    location.hash = '#/builder';
    if (located) setTimeout(() => SX.revealNode?.(issue.nodeId), 0);
  }

  function checksPanel(sc) {
    const issues = issuesFor(sc);
    const has = rules => issues.filter(i => rules.includes(i.rule));
    const collections = A.collectionsUsed(project());
    const unknown = has(['unknown-module']);
    const check = (ok, okText, badText, severity = 'warn') => el('div', { class: `check-item${ok ? '' : ` ${severity}`}` }, [icon(ok ? 'checkLarge' : severity === 'error' ? 'info' : 'warning', 15), el('span', { text: ok ? okText : badText })]);
    const yamlErrors = has(['yaml']);
    const required = has(['missing-required', 'no-module', 'no-hosts', 'role-missing']);
    const notify = has(['notify-handler']);
    const undefinedVars = has(['undefined-var']);
    const unnamed = has(['name-missing']);
    const cards = issues.filter(i => i.severity === 'error' || ['no-changed-when', 'notify-handler', 'undefined-var', 'unknown-arg', 'empty-play', 'empty-block', 'unknown-role'].includes(i.rule));
    return el('aside', { class: 'panel', style: 'border-left: 0', attrs: { 'aria-label': 'Checks' } }, [
      el('div', { class: 'panel-section' }, [
        el('div', { class: 'panel-title-row' }, [el('h2', { class: 'panel-title', text: 'Checks' }), el('span', { class: 'field-hint', text: 'lint · built in' })]),
        check(!yamlErrors.length, 'Valid YAML and playbook syntax', yamlErrors[0]?.message || '', 'error'),
        check(!unknown.length, collections.length ? `Every module resolves — ${collections.join(', ')} listed in requirements.yml` : 'Every module resolves', `${SX.plural(unknown.length, 'task')} use modules that aren’t in an installed module set (kept exactly as written)`),
        check(!required.length, 'Every required parameter and play target is filled in', `${SX.plural(required.length, 'block')} ${required.length === 1 ? 'is' : 'are'} missing something required`, 'error'),
        check(!notify.length, 'Every notify points at a handler', `${SX.plural(notify.length, 'notify', 'notifies')} point at missing handlers`),
        check(!undefinedVars.length, 'Variables in use are all defined', `Undefined: ${[...new Set(undefinedVars.flatMap(i => i.names))].join(', ')}`),
        unnamed.length ? check(false, '', `${SX.plural(unnamed.length, 'task has', 'tasks have')} no name`) : null,
        ...cards.map(issue => el('div', { class: `callout ${issue.severity === 'error' ? 'error' : 'warn'}`, style: 'flex-direction: column; gap: 8px; padding: 12px' }, [
          el('div', { class: 'panel-title-row' }, [
            el('span', { style: `display: flex; align-items: center; gap: 8px; font: 600 12.5px/1 var(--font-mono); color: ${issue.severity === 'error' ? 'var(--danger-text)' : 'var(--warn-strong)'}` }, [icon(issue.severity === 'error' ? 'info' : 'warning', 15), issue.rule]),
            el('span', { class: 'mono', style: 'font-size: 11.5px; opacity: .8', text: lineOf(sc, issue) })
          ]),
          el('span', { text: issue.message }),
          el('div', { style: 'display: flex; gap: 8px; flex-wrap: wrap' }, [
            issue.fix ? el('button', { class: 'btn btn-sm btn-warn-solid', type: 'button', text: issue.fix.label, onclick: () => store.commit(p => { const n = SX.findNode(p, issue.nodeId); if (n) issue.fix.apply(n); }, { source: 'export' }) }) : null,
            issue.nodeId ? el('button', { class: 'btn btn-sm', type: 'button', text: 'Show block', onclick: () => showBlock(issue) }) : null
          ])
        ]))
      ]),
      el('div', { class: 'panel-section' }, [
        el('div', { class: 'panel-title-row' }, [el('h2', { class: 'panel-title', text: 'What’s in the download' }), el('span', { class: 'mono faint', style: 'font-size: 12px', text: sc.name })]),
        el('div', { class: 'tree' }, sc.kind === 'yml'
          ? sc.files.map(f => el('div', { class: 'tree-row' }, [el('span', { class: 'color-square', style: `--c: ${KIND_COLORS[f.kind]}` }), f.path]))
          : [el('div', { class: 'tree-row' }, [el('span', { class: 'color-square', style: '--c: #F4C542' }), `${sc.name.replace(/\.(zip|tar\.gz)$/, '')}/`]), ...treeRows(sc.files)])
      ])
    ]);
  }

  // Files collapsed to one row per role folder, as in the reference.
  function treeRows(files) {
    const rows = [];
    const seenRoles = new Set();
    for (const f of files) {
      const roleMatch = f.path.match(/^(roles\/[^/]+\/)/);
      if (roleMatch) {
        if (seenRoles.has(roleMatch[1])) continue;
        seenRoles.add(roleMatch[1]);
        rows.push(el('div', { class: 'tree-row', style: 'padding-left: 16px' }, [el('span', { class: 'color-square', style: `--c: ${KIND_COLORS.role}` }), roleMatch[1]]));
        continue;
      }
      rows.push(el('div', { class: 'tree-row', style: 'padding-left: 16px' }, [el('span', { class: 'color-square', style: `--c: ${KIND_COLORS[f.kind] || '#C3CCDB'}` }), f.path]));
    }
    return rows;
  }

  // ---- Actions -----------------------------------------------------------------------------------

  async function download(sc) {
    if (sc.kind === 'yml') {
      ui.download(new Blob([sc.files[0].content], { type: 'text/yaml;charset=utf-8' }), sc.name);
      return;
    }
    if (sc.kind === 'role') {
      try {
        ui.download(await SX.Archive.tarGz(sc.files), sc.name);
      } catch (error) {
        ui.toast(`Couldn’t build the archive: ${error.message}`);
      }
      return;
    }
    const root2 = sc.name.replace(/\.zip$/, '');
    ui.download(SX.Archive.zip(sc.files.map(f => ({ path: `${root2}/${f.path}`, content: f.content }))), sc.name);
  }

  function render() {
    const sc = scope();
    const issues = issuesFor(sc);
    const errors = issues.filter(i => i.severity === 'error').length;
    const warnings = issues.filter(i => i.severity === 'warning' && i.rule !== 'name-missing').length;
    const status = errors ? el('span', { class: 'pill', style: 'background: #2A1719; color: var(--danger-text)' }, [icon('info', 13), `${SX.plural(errors, 'error')} to fix`])
      : warnings ? el('span', { class: 'pill warn' }, [icon('warning', 13), `Ready · ${SX.plural(warnings, 'warning')}`])
      : el('span', { class: 'pill ok' }, [icon('checkLarge', 13), 'Ready']);
    const file = sc.files.find(f => f.path === state.file) || sc.files[0];
    const scroll = root.querySelector('.code')?.scrollTop;
    root.replaceChildren(
      el('div', { class: 'page-head', style: 'min-height: 68px' }, [
        el('a', { class: 'back-link', href: '#/builder' }, [icon('back', 16), 'Builder']),
        el('h1', { class: 'page-title', text: 'Export for use' }),
        el('span', { class: 'grow' }),
        status
      ]),
      el('div', { class: 'cols', style: 'grid-template-columns: 340px minmax(0, 1fr) 360px' }, [optionsPanel(), filesPane(sc), checksPanel(sc)]),
      el('div', { class: 'actionbar', style: 'min-height: 72px' }, [
        el('span', { style: 'display: flex; align-items: center; gap: 10px; font: 400 13px/1.4 var(--font-ui); color: var(--text-soft)' }, [el('span', { style: 'color: var(--ok); display: flex' }, icon('shield', 18)), 'Plain Ansible out — runs with ', el('span', { class: 'mono', text: 'ansible-playbook' }), ', no Scransible needed.']),
        el('span', { class: 'grow' }),
        errors ? el('span', { class: 'field-hint', style: 'color: var(--danger-text)', text: 'Fix the errors above to download.' }) : null,
        el('button', { class: 'btn', type: 'button', disabled: !file, onclick: async () => ui.toast(await ui.copy(file.content) ? `Copied ${file.path}.` : 'Could not copy.') }, [icon('copy', 16), 'Copy this file']),
        el('button', { class: 'btn btn-primary', type: 'button', disabled: !!errors || !sc.files.length, onclick: () => download(sc) }, [icon('import', 16, 2), 'Download ', el('span', { class: 'mono', style: 'font-weight: 600', text: sc.name })])
      ])
    );
    if (scroll) root.querySelector('.code').scrollTop = scroll;
  }

  SX.pages = SX.pages || {};
  SX.pages.export = {
    mount(container) {
      SX.DnD.handler = null;
      root = el('div', { class: 'page with-head', style: 'grid-template-rows: auto minmax(0, 1fr) auto; min-height: 0' });
      container.replaceChildren(root);
      state.file = null;
      render();
    },
    update() { render(); }
  };
})();
