#!/usr/bin/env python3
"""Build the builder's keyword catalog from `ansible-doc -t keyword`.

Usage:
    python3 tools/build-keywords.py > src/keywords.js

Every playbook keyword Ansible documents is included, with the objects it applies to
(play, role, block, task, handler), its type and its description. tools/keywords.json
adds the slot kind the builder uses, menu groups, labels, and suggested values (for
example become_method suggests the become plugins installed where ansible-doc runs).
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TYPE_KINDS = {'bool': 'bool', 'int': 'int', 'float': 'int', 'percent': 'int', 'string': 'str', 'list': 'list', 'dict': 'yaml', 'class': 'yaml'}


def run(*args):
    return subprocess.run(['ansible-doc', *args], capture_output=True, text=True, check=True).stdout


def plugin_names(kind, first):
    names = sorted(json.loads(run('-t', kind, '-l', '-j')))
    short = [n.split('.', 2)[2] if n.startswith('ansible.builtin.') else n for n in names]
    return list(dict.fromkeys(first + short))


def clean(text):
    text = re.sub(r':(?:term|ref):`([^`<]*?)(?:\s*<[^>]+>)?`', r'\1', text)
    return re.sub(r'\s+', ' ', text.replace('`', '')).strip()


def main():
    spec = json.load(open(os.path.join(HERE, 'keywords.json')))
    names = re.findall(r'^([a-z_<>]+):', run('-t', 'keyword', '-l'), re.M)
    docs = json.loads(run('-t', 'keyword', '-j', *names))
    # Keys Ansible accepts but doesn't document as keywords (listen on handlers, local_action).
    docs.update(spec.get('extra', {}))
    group_of = {name: group for group, members in spec['groups'].items() for name in members}
    keywords = {}
    for name in sorted(docs):
        doc = docs[name]
        entry = {
            'kind': spec['kinds'].get(name) or TYPE_KINDS.get(doc.get('type'), 'str'),
            'appliesTo': [a.lower() for a in doc['applies_to']],
            'doc': clean(doc.get('description', ''))[:240]
        }
        if name in spec['structural']:
            entry['structural'] = True
        if name in spec['labels']:
            entry['label'] = spec['labels'][name]
        if name in group_of:
            entry['group'] = group_of[name]
        suggest = spec['suggest'].get(name)
        if suggest:
            values = suggest.get('values') or plugin_names(suggest['plugins'], suggest.get('first', []))
            entry['suggest'] = values
            if 'values' in suggest:
                entry['kind'] = 'choice'
        keywords[name] = entry
    version = run('--version').split('\n')[0].split('core ')[-1].strip(' ]')
    data = {'ansible': version, 'keywords': keywords}
    print('// Generated by tools/build-keywords.py from ansible-doc and tools/keywords.json.')
    print('// Regenerate rather than changing this file by hand.')
    body = ',\n'.join(f'    {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}' for k, v in keywords.items())
    print(f'Scransible.registerKeywords({{\n  "ansible": {json.dumps(version)},\n  "keywords": {{\n{body}\n  }}\n}});')


if __name__ == '__main__':
    if len(sys.argv) != 1:
        sys.exit(__doc__)
    main()
